# Generated by Django 2.2.4 on 2022-12-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0002_show_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='shows',
        ),
        migrations.AddField(
            model_name='show',
            name='network',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
